M48
; DRILL file {KiCad (6.0.6-0)} date 2024 April 04, Thursday 07:50:39
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-04T07:50:39+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.7944Y-3.4566
X3.7944Y-3.6534
T2
X3.69Y-1.41
X3.69Y-4.36
X5.7339Y-1.41
X5.7339Y-4.36
T0
M30
