M48
; DRILL file {KiCad (6.0.6-0)} date 2025 March 25, Tuesday 10:56:29
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-25T10:56:29+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X7.7961Y-1.36
X7.7961Y-3.51
X8.99Y-1.36
X8.99Y-3.51
T0
M30
